### ISSUE TITLE
Jarelllamas_Scam_Blocklist.png

### ISSUE THREAD

**Issue by jarelllama** [iam-py-test/blocklist_stats#1]
I just discovered this repo. Interesting stuff!

Mind if I use https://github.com/iam-py-test/blocklist_stats/blob/main/stats/Jarelllamas_Scam_Blocklist.png in my README?

**Comment by jarelllama** [comment]
Also if you're interested, you could track the light version of my blocklist too: https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/adblock/scams_light.txt

**Comment by iam-py-test** [comment]
> Mind if I use https://github.com/iam-py-test/blocklist_stats/blob/main/stats/Jarelllamas_Scam_Blocklist.png in my README?

I have no objection to you (or anyone else) using these graphs.
> Also if you're interested, you could track the light version of my blocklist too:

Added, thanks. The graph should be automatically created around 4 PM Eastern Standard Time/20:00 UTC.

**Comment by iam-py-test** [comment]
As you question appears to have been answered, I will close the issue.

**Comment by jarelllama** [comment]
@hagezi you can consider adding your graph in your repo.
